name: Documentation PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'website/**'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: pnpm/action-setup@v3
        name: Setup pnpm
        with:
          version: 10.12.1

      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: 24.2
          cache: 'pnpm'
          cache-dependency-path: 'website/pnpm-lock.yaml'
          
      - name: Test Build
        run: |
          cd website
          if [ -e pnpm-lock.yaml ]; then
          pnpm install --frozen-lockfile
          elif [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          pnpm install
          fi
          pnpm run build
